blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.details, name="details")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path('blog/', include('blog.urls')),
    path("portfolio/contact/", views.contact_me, name="contact_me"),
    path("<int:tech_card_number>/", views.tech_stack_view, name="tech_stack_view"),
    path("portfolio/received/", views.show_emails, name="show_emails")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    summary_header = models.CharField(max_length=100)
    description = models.TextField(max_length=20000)
    date = models.DateField()
    #image = models.ImageField(upload_to="blog/images/")

    def __str__(self):
        return self.summary_header

portfolio/models.py
import django

from django.db import models
from django.core.validators import EmailValidator, ProhibitNullCharactersValidator


class Project(models.Model):
    project_name = models.CharField(max_length=100)
    from_date = models.DateField()
    to_date = models.DateField(blank=True, null=True, auto_now_add=False)
    role = models.CharField(max_length=100)
    description = models.TextField(max_length=10000)
    responsibilities = models.TextField(max_length=10000, blank=True)

    def __str__(self):
        return self.project_name


class ProjSummary(models.Model):
    title = models.CharField(max_length=100)
    summary = models.TextField(max_length=10000)

    def __str__(self):
        return self.title


class ProjSkills(models.Model):
    skill = models.TextField(max_length=500)


class ProjTools(models.Model):
    tool = models.TextField(max_length=500)


class OperatigSystems(models.Model):
    os_system = models.TextField(max_length=500)


class PersonalSkills(models.Model):
    personal_skills = models.TextField(max_length=1000)


class ProjTechStack(models.Model):
    tech_image = models.ImageField(upload_to="portfolio/tools/")
    tech_summary = models.CharField(max_length=100)
    tech_description = models.TextField(max_length=10000)
    tech_image_name_static = models.CharField(max_length=100)

    def __str__(self):
        return self.tech_summary


class ProjTechStackNew(models.Model):
    tech_image_name_static = models.CharField(max_length=100)
    tech_summary = models.CharField(max_length=100)
    tech_description = models.TextField(max_length=10000)

    def __str__(self):
        return self.tech_summary


class DomainKnowledge(models.Model):
    domains = models.TextField(max_length=1000)


class PythonExpossure(models.Model):
    python_header = models.CharField(max_length=500)
    python_sk = models.TextField(max_length=1000)

    def __str__(self):
        return self.python_header


class Education(models.Model):
    university = models.CharField(max_length=100)
    degree = models.CharField(max_length=100)
    year_from = models.DateField()
    year_to = models.DateField()

    def __str__(self):
        return self.university


class ContactME(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=100)
    create_date = models.DateTimeField(default=django.utils.timezone.now)

    def __str__(self):
        return self.name + self.email

portfolio/forms.py
from django import forms
from .models import ContactME


class ContactMeForm(forms.ModelForm):

    class Meta:
        model = ContactME
        fields = ['name', 'email', 'subject', 'message']
        

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.all()
    #blogs = Blog.objects.order_by('-date')
    return render(request, "blog/all_blogs.html", {"blogs": blogs})


def details(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, HttpResponseRedirect, redirect
from .models import Project, ProjSummary, ProjSkills, ProjTools, ProjTechStack, OperatigSystems, PersonalSkills, \
    DomainKnowledge, PythonExpossure, Education, ContactME, ProjTechStackNew
from .forms import ContactMeForm


def home(request):
    projects = Project.objects.all()
    profile = ProjSummary.objects.all()[:1]
    skills = ProjSkills.objects.all()
    tools = ProjTools.objects.all()
    techstacks = ProjTechStack.objects.all()
    os_sys = OperatigSystems.objects.all()
    personal_skills = PersonalSkills.objects.all()
    domain_skills = DomainKnowledge.objects.all()
    python_skills = PythonExpossure.objects.all()
    educations = Education.objects.all()
    return render(request, "portfolio/home.html",
                  {"projects": projects, "profile": profile, "skills": skills, "tools": tools,
                   "techstacks": techstacks, "os_sys": os_sys, "personal_skills": personal_skills,
                   "domain_skills": domain_skills, "python_skills": python_skills, "educations": educations})


def tech_stack_view(request, tech_card_number):
    techstack = get_object_or_404(ProjTechStack, pk=tech_card_number)
    description = techstack.tech_description
    return render(request, "portfolio/tech_stack.html", {'techstack': techstack})

def tech_stack_view_static(request, tech_card_number):
    techstack = get_object_or_404(ProjTechStackNew, pk=tech_card_number)
    return render(request, "portfolio/tech_stack.html", {'techstack': techstack})

def contact_me(request):
    if request.method == "POST":
        form = ContactMeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(status=204) #return no content
    else:
        form = ContactMeForm()
    return render(request, 'portfolio/email.html', {'form': form})


def show_emails(request):
    emails = ContactME.objects.order_by('-create_date')
    return render(request, 'portfolio/received.html', {"emails": emails})

# def tech_stack_view(request, tech_card_number):
#     if request.method == "POST":
#         techstack = TechStackForm(request.POST, pk=tech_card_number)
#         if techstack.is_valid():
#             techstack.save()
#             return redirect('/')
#     else:
#         techstack = TechStackForm()
#     return render(request, "portfolio/tech_stack.html", {'techstack': techstack})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
    {% load static %}

       <div class="Container text-left">
            {% for blog in blogs %}
           <div class="col-xl-10 offset-xl-1">
                <div class="col-lg" align="left">
                   <div class="row">
                        {% if forloop.counter|divisibleby:"2" %}

                            <section id="sc1_blogs_{{blog.id}}"  class="sec-color-alternate" xmlns="http://www.w3.org/1999/html">
                                {% else %}
                                <section id="sc_blogs_{{blog.id}}"  class="sec-color" xmlns="http://www.w3.org/1999/html">
                           {% endif %}
                           <div id="blog_{{ blog.id}}" class="col" >
                             <h4><a href="#blogs_{{ blog.id}}" data-toggle="collapse" align="left">{{ forloop.counter }}. {{ blog.summary_header }}</a>
                                </h4>

                           </div>

                            <div class="collapse" id="blogs_{{ blog.id }}">
                                <div class="col" align="left">
                             <p> {{ blog.description|safe }}</p>
                                    </div>
                                <div class="col" align="right">
                                <h5 class="gray-text" >{{ blog.date|date:'M d Y' }}</h5>
                                </div>
                             </div>
                         </section>

                   </div>
                </div>
           </div>
            {% endfor %}
       </div>


{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <h2>{{ blog.summary_header }}</h2>
      <div class="Container text-left">
            {% for blog in blogs %}
           <div class="col-xl-10 offset-xl-1">
               <div class="row">
                <section id="sc_blogs_{{blog.id}}"  class="sec-color-alternate" xmlns="http://www.w3.org/1999/html">
                    <a><h2>{{ blog.summary_header }}</h2></a>
                    <br>
                    <p> {{ blog.description|safe }}</p>
                    <br>
                    <p> {{ blog.date|date:'M d Y' }}</p>
                </section>
               </div>
            {% endfor %}
               </div>
           </div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
{% load static %}
<style>

</style>
  <head>

    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
      <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!--  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet" type='text/css'>-->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700:&display=swap" rel="stylesheet" type='text/css'>


  <link rel="icon" type="image/png" href="{% static 'portfolio/Logo.png' %}">

  <title>Ashish Chincholkar</title>
  </head>
  <body>

    {% load static %}
    <nav id="topNav" class="navbar fixed-top navbar-expand-lg bg-light navbar-light" >
       <div class="container">

        <div class="navbar-header navbar-collapse text-center" id="navbarNav">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav_target" aria-label="toggle nav">
              <span class="navbar-toggler-icon"></span>
            </button>
          <a class="navbar-brand" href="{% url 'home' %}">
           <img src="{% static 'portfolio/logo.png' %}" width="40" height="30" class="d-inline-block align-top" alt="ashish's Logo">
           <span>Ashish Chincholkar</span>
        </a>

            </div>
        <div class="navbar-collapse collapse" id="nav_target">
             <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#exp_summary">Experience</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#exp_keyskills">Skills</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#personal_skills">Personal Skills</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="#python_skills">Python Skills</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#tech_stack">Tech Stacks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#domain_skills">Domain</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/Resume1.pdf' %}" target="_blank">CV</a>
          </li>
            <li class="nav-item">
<!--            <a class="nav-link" href="#domain_skills">Education</a>-->
                <a class="nav-link" href="#education">
              <img  src="{% static 'portfolio/Education.png' %}" width="35" height="30" class="d-inline-block align-top" alt="Education" ></a>
          </li>
          <li class="nav-item">
<!--            <a class="nav-link" href="https://www.linkedin.com/in/ashishkumar-chincholkar-79126225" target="_blank">-->
            <a class="nav-link" href="https://www.linkedin.com/in/ashishkumar-chincholkar-79126225" target="_blank">
              <img  src="{% static 'portfolio/linkdin.png' %}" width="25" height="25" class="d-inline-block align-top" alt="linkedin" ></a>
          </li>

          <li class="nav-item">
<!--            <a class="nav-link" href="#domain_skills">Contact</a>-->
              <a  class="btn btn-light" hx-get="{% url 'contact_me' %}" hx-target="#dialog">
              <img src="{% static 'portfolio/ContactMe.png' %}" width="25" height="25" class="d-inline-block align-top" alt="ContactMe" ></a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>

        </ul>
        </div>

      </div>
    </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://unpkg.com/htmx.org@1.8.4"></script>
  <script src="{% static 'portfolio/dialog.js' %}"></script>

  </body>

<script>
$(".navbar-collapse a").click(function () {
  $(".navbar-collapse").collapse("hide");
});
</script>
</html>

portfolio/templates/portfolio/email.html
{% load widget_tweaks %}
{% block content %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" class="modal-content">
  {% csrf_token %}
  <div class="modal-header">
    <h5>Contact Me</h5>
    <button type="button" class="btn-close" aria-label="Close" data-dismiss="modal"></button>
  </div>
  <div class="modal-body">
    <div class="mb-3">
        <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
        {% render_field form.name class="form-control" placeholder="Name" %}
        <div class="Invalid-feedback">{{ form.name.error|first }}</div>
    </div>
      <div class="mb-3">
        <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
        {% render_field form.email class="form-control" placeholder="Email" %}
        <div class="Invalid-feedback">{{ form.email.error|first }}</div>
      </div>
       <div class="mb-3">
        <label for="{{ form.subject.id_for_label }}" class="form-label">Subject</label>
        {% render_field form.subject class="form-control" placeholder="Subject" %}
        <div class="Invalid-feedback">{{ form.email.error|first }}</div>
      </div>
      <div class="mb-3">
        <label for="{{ form.message.id_for_label }}" class="form-label">Message</label>
        {% render_field form.message class="form-control" placeholder="Hello Ashish, " %}
        <div class="Invalid-feedback">{{ form.email.error|first }}</div>
      </div>
  </div>
  <div class="modal-footer">
      <button type="submit" class="btn btn-primary" onclick="alert('thank you for your email');">Send Email</button>

  </div>
</form>
{% endwith %}
{% endblock %}

portfolio/templates/portfolio/received.html
{% extends 'portfolio/base.html' %}
{% block content %}
    {% load static %}
    <section id="emails">
        <div class="text-left">

        {% for email in emails %}
        <div class="row">
        <ul>
            <li>
                {{ email.name }} - {{ email.create_date}} - {{ email.email}}
                <p> <b>Subject:</b> {{ email.subject }}</p>
                <p> {{email.message }}</p>
            </li>
        </ul>
        {% endfor %}
        </div>

        </div>
    </section>

{% endblock %}

portfolio/templates/portfolio/tech_stack.html
{% block content %}
<div class="modal-dialog modal-dialog-centered">
<div hx-post="{{ request.path }}" action="{{ request.path }}" class="modal-content" >
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title"><b>{{ techstack.tech_summary }}</b></h5>
    <button type="button" class="btn-close" aria-label="Close" data-dismiss="modal"></button>
  </div>
  <div class="modal-body">
    {{ techstack.tech_description|safe }}
  </div>
  <div class="modal-footer">
  </div>
    </div>
</div>
{% endblock %}



<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->


<!--  <title>{{ techstack.tech_summary }}</title>-->
<!--  </head>-->


<!--<body>-->
<!--    <div id="popup" class="modal fade" role="dialog">-->
<!--      <div class="modal-dialog modal-lg">-->
<!--        <div class="modal-content">-->
<!--          <div class="modal-body">-->
<!--              <p class="bg-info text-white pl-2">-->
<!--              {{ techstack.tech_description }}-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="modal-footer">-->
<!--            <button type="button" class="btn btn-info" data-dismiss="modal">Close-->
<!--            </button>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--</div>-->
<!--</body>-->

<!-- To place above the incident-modal html -->
<!--<script>-->

<!--</script>-->
<!--</html>-->